
interface BugoutUser {
    id: string
    username: string
    first_name?: string
    last_name?: string
    email?: string
    normalized_email?: string
    verified?: string
    autogenerated?: string
    application_id?: string
    created_at?: string
    updated_at?: string
}

declare class BugoutClient {
    constructor(
        broodUrl: string,
        spireUrl: string,
        filesUrl: string
    )

    greeting: string;
    getUser(token: string): BugoutUser;
}